export enum ShipmentStatus {
    ORDER_CREATED = 1,
    IN_PREPARATION = 2,
    IN_TRANSIT = 3,
    OUT_FOR_DELIVERY = 4,
    DELIVERED = 5,
    CANCELLED = 6,
    EXTRAVIADO = 7,
    DANIFICADO = 8,
    ENDERECO_INVALIDO = 9,
    DESTINATARIO_AUSENTE = 10,
}
